name: Deploy via Dependabot Pull Request

on:
    pull_request_target:
        branches:
            - $default-branch
            - develop

env:
    php: 8.1
    node: 16

concurrency:
    group: ${{ github.sha }}

permissions:
    pull-requests: write
    issues: write
    repository-projects: write
    contents: write

jobs:
    install_project:
        uses: agence-adeliom/github-actions/.github/workflows/callable-install-project.yml@main
        with:
            php: ${{ env.php }}
            node: ${{ env.node }}

    auto_approve_and_merge:
        needs: [ install_project ]
        uses: agence-adeliom/github-actions/.github/workflows/callable-approve-merge.yml@main

    deploy:
        needs: [ auto_approve_and_merge ]
        if: ${{ needs.auto_approve_and_merge.outputs.canMerge == 'success' }}
        uses: agence-adeliom/github-actions/.github/workflows/callable-deploy-only.yml@main
        secrets:
            DEPLOYER_INVENTORY: ${{ secrets.DEPLOYER_INVENTORY }}
            PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
