name: Deploy Only Manually

on:
    workflow_dispatch:
        inputs:
            HOST:
                required: true
                type: choice
                description: ""
                default: "staging"
                options:
                    - production
                    - staging
            BRANCH:
                description: ""
                required: false
                default: "develop"
                type: string

concurrency: adeliom_deploy

jobs:
    deploy_manually:
        name: Déploiement manuel
        uses: agence-adeliom/github-actions/.github/workflows/callable-deployer-deploy-only.yml@main
        with:
            branch: ${{ inputs.branch }}
        secrets:
            DEPLOYER_INVENTORY: ${{ secrets.DEPLOYER_INVENTORY }}
            PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}