name: Deploy Only

on:
    workflow_call:
        inputs:
            branch:
                required: false
                description: "La branche à utiliser"
                type: string

permissions:
    pull-requests: write
    issues: write
    repository-projects: write
    contents: write

concurrency: adeliom_deploy

jobs:
    deploy:
        name: Déploiement
        runs-on: ubuntu-latest
        steps:
            - name: Définition de la variable HOST pour env production
              if: ${{ (inputs.branch && inputs.branch == 'prod') || github.ref_name == 'prod' }}
              run: echo "HOST=production" >> $GITHUB_ENV
              shell: bash

            - name: Définition de la variable HOST pour env staging
              if: ${{ (inputs.branch && inputs.branch == 'recette') || github.ref_name == 'recette' }}
              run: echo "HOST=staging" >> $GITHUB_ENV
              shell: bash

            - uses: actions/checkout@v3

            - name: Retrieve the secret inventory and decode it to a file
              env:
                  DEPLOYER_INVENTORY: ${{ secrets.DEPLOYER_INVENTORY }}
              run: |
                  echo $DEPLOYER_INVENTORY | base64 --decode > inventory.yaml

            - name: Deploy branch ${{ inputs.branch || github.ref_name }} to ${{ env.HOST }}
              uses: deployphp/action@v1
              with:
                  deployer-version: "7.0.2"
                  private-key: ${{ secrets.PRIVATE_KEY }}
                  dep: deploy --branch=${{ inputs.branch || github.ref_name }} -n ${{ env.HOST }}