name: Install project libs and compile

on:
    workflow_call:
        inputs:
            php:
                required: true
                type: string
                default: "8.1"
            node:
                required: true
                type: string
                default: "18"
            working-directory:
                required: false
                type: string
                default: "."

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
             # On copie le repo
            - uses: actions/checkout@v3

            # On installe PHP
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ inputs.php }}

            # On créé le cache de composer pour prendre moins de temps à build
            - name: Get Composer Cache Directory
              id: composer-cache
              working-directory: ${{ inputs.working-directory }}
              run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            # On récupère le cache de composer du step précédent
            - uses: actions/cache@v3
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ inputs.working-directory }}-${{ hashFiles(format('{0}/composer.lock', inputs.working-directory)) }}
                  restore-keys: |
                      ${{ runner.os }}-composer-${{ inputs.working-directory }}-${{ hashFiles(format('{0}/composer.lock', inputs.working-directory)) }}
                      ${{ runner.os }}-composer-${{ inputs.working-directory }}-

            - name: Check Composer lock file is up to date
              working-directory: ${{ inputs.working-directory }}
              run: composer validate --no-check-all

            - name: Install Composer dependencies
              working-directory: ${{ inputs.working-directory }}
              run: composer install --no-progress --prefer-dist --optimize-autoloader

            # On install NodeJS
            - name: Check file existence
              id: check_files
              uses: andstor/file-existence-action@v2
              with:
                files: "${{ inputs.working-directory }}/package-lock.json"

            - uses: actions/setup-node@v3
              if: steps.check_files.outputs.files_exists == 'true'
              with:
                  node-version: ${{ inputs.node }}
                  cache: npm
                  cache-dependency-path: '${{ inputs.working-directory }}/package-lock.json'

            # On install les dependances Node
            - name: Install NPM dependencies
              if: steps.check_files.outputs.files_exists == 'true'
              working-directory: ${{ inputs.working-directory }}
              run: npm ci

            # On joue les tests front
            - name: Run NPM test suite
              if: steps.check_files.outputs.files_exists == 'true'
              working-directory: ${{ inputs.working-directory }}
              run: npm run test --if-present

            # On build le front
            - name: Try to build theme's assets
              if: steps.check_files.outputs.files_exists == 'true'
              working-directory: ${{ inputs.working-directory }}
              run: npm run build --if-present
