name: Dependabot Symfony Update

on:
    workflow_call:
        inputs:
            php:
                required: true
                type: string
                default: "8.1"
            node:
                required: true
                type: string
                default: "18"

# The commit SHA that triggered the workflow.
# Pour éviter un double run sur le pull_target / pull_request_target
concurrency:
    group: ${{ github.sha }}

permissions:
    pull-requests: write
    issues: write
    repository-projects: write
    contents: write

jobs:
    auto_approve_and_merge:
        runs-on: ubuntu-latest
        if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
        env:
            PR_URL: ${{github.event.pull_request.html_url}}
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        steps:
            # On copie le repo
            - uses: actions/checkout@v3

            # On récupère les infos de la PR de Dependabot
            - name: Fetch Dependabot metadata
              id: metadata
              uses: dependabot/fetch-metadata@v1.3.3
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}

            # On approve et merge la PR de Dependabot seulement si la version de la lib maj n'est pas majeure
            - name: Enable auto-approve/merge for Dependabot PRs
              if: steps.metadata.outputs.update-type != 'version-update:semver-major'
              run: |
                gh pr review --approve "$PR_URL"
                gh pr merge --auto --merge "$PR_URL"
