name: Deployer Lumberjack

on:
  workflow_call:
    inputs:
      php:
        required: true
        type: string
        default: "8.1"
      node:
        required: true
        type: string
        default: "18"
      branch:
        required: true
        type: string
      deployer:
        required: false
        type: string
        default: "7.0.2"
      theme:
        required: false
        type: string
        default: "adeliom"
    secrets:
      PRIVATE_KEY:
        required: true
      DEPLOYER_INVENTORY:
        required: true
      GRAVITYFORMS_KEY:
        required: true
      ACF_PRO_KEY:
        required: true

concurrency: production_environment

jobs:
  install:
    uses: agence-adeliom/github-actions/.github/workflows/callable-lumberjack-install.yml@main
    with:
      theme: ${{ inputs.theme }}
      php: ${{ inputs.php }}
      node: ${{ inputs.node }}
  deployer:
    name: 🎉 Setup Deployer
    runs-on: ["self-hosted", "ubuntu"]
    needs: ["install"]
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: ${{ inputs.php }}
        env:
          runner: self-hosted

      - uses: actions/cache@v3
        with:
            path: ${{ steps.composer-cache.outputs.dir }}
            key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
            restore-keys: |
                ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: Check Composer lock file is up to date
        run: composer validate --no-check-all

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Définition du host
        if: ${{ inputs.BRANCH == 'main' || inputs.BRANCH == 'master' }}
        run: echo "HOST=production" >> $GITHUB_ENV
        shell: bash

      - name: Définition du host
        if: ${{ inputs.BRANCH == 'develop' }}
        run: echo "HOST=staging" >> $GITHUB_ENV
        shell: bash

      - name: Récupération du repository
        if: ${{ env.HOST }}
        uses: actions/checkout@v3

      - name: Retrieve the secret inventory and decode it to a file
        env:
          DEPLOYER_INVENTORY: ${{ secrets.DEPLOYER_INVENTORY }}
        run: |
          echo $DEPLOYER_INVENTORY | base64 --decode > inventory.yaml
      - name: Deploy
        uses: deployphp/action@v1
        with:
          deployer-version: ${{ inputs.deployer }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          dep: deploy --branch=${{ inputs.BRANCH }} -n ${{ env.HOST }}
