name: Approve and Merge Dependabot PR

on:
    workflow_call:
        merge_type:
            description: "Must be one of 'merge', 'rebase' or 'squash'. Default: 'merge'"
            required: false
            type: string
            default: "merge"
        outputs:
            canMerge:
                description: "Est-ce que la PR peut être mergée ?"
                value: ${{ jobs.auto_approve_and_merge.outputs.canMerge }}

jobs:
    auto_approve_and_merge:
        runs-on: "ubuntu-latest"
        outputs:
            canMerge: ${{ steps.canMerge.outputs.canMerge }}
        if: ${{ github.actor == 'dependabot[bot]' }}
        env:
            PR_URL: ${{github.event.pull_request.html_url}}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - uses: actions/checkout@v3

            - name: Fetch Dependabot metadata
              id: metadata
              uses: dependabot/fetch-metadata@v1.3.3
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}

            - name: Enable auto-approve for Dependabot PRs
              run: gh pr review --approve "$PR_URL"

            - name: Enable auto-approve/${{ inputs.merge_type }} for Dependabot PRs
              id: prMerge
              continue-on-error: true
              run: |
                  if [[ "${{ steps.metadata.outputs.update-type }}" != 'version-update:semver-major' ]]; then
                    echo "status=pending" >> $GITHUB_OUTPUT
                    gh pr review --approve "$PR_URL"
                    echo "status=approved" >> $GITHUB_OUTPUT
                    gh pr merge --auto --${{ inputs.merge_type }} "$PR_URL"
                    echo "status=updated" >> $GITHUB_OUTPUT
                  else
                    echo "status=skipped" >> $GITHUB_OUTPUT
                  fi

            - name: Output can merge ?
              id: canMerge
              run: echo "canMerge=${{steps.prMerge.outcome}}" >> $GITHUB_OUTPUT
              shell: bash
