name: Deploy Only

on:
    workflow_call:
        inputs:
            branch:
                required: false
                description: "La branche à utiliser"
                type: string
        secrets:
            DEPLOYER_INVENTORY:
                required: true
            PRIVATE_KEY:
                required: true

permissions:
    pull-requests: write
    issues: write
    repository-projects: write
    contents: write

concurrency: adeliom_deploy

jobs:
    deploy:
        name: Déploiement
        runs-on: adeliom
        steps:
            -   uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ inputs.php }}
                env:
                    runner: self-hosted

            -   name: Get Composer Cache Directory
                id: composer-cache
                run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            -   uses: actions/cache@v3
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

            -   name: Check Composer lock file is up to date
                run: composer validate --no-check-all

            -   name: Install Composer dependencies
                run: composer install --no-progress --prefer-dist --optimize-autoloader

            - name: Définition de la variable HOST pour env production
              if: ${{ ((inputs.branch && inputs.branch == 'prod') || github.ref_name == 'prod') || ((inputs.branch && inputs.branch == 'master') || github.ref_name == 'master') }}
              run: echo "HOST=production" >> $GITHUB_ENV
              shell: bash

            - name: Définition de la variable HOST pour env staging
              if: ${{ ((inputs.branch && inputs.branch == 'recette') || github.ref_name == 'recette') || ((inputs.branch && inputs.branch == 'develop') || github.ref_name == 'develop') }}
              run: echo "HOST=staging" >> $GITHUB_ENV
              shell: bash

            - uses: actions/checkout@v3

            - name: Retrieve the secret inventory and decode it to a file
              env:
                  DEPLOYER_INVENTORY: ${{ secrets.DEPLOYER_INVENTORY }}
              run: |
                  echo $DEPLOYER_INVENTORY | base64 --decode > inventory.yaml

            - name: Deploy branch ${{ inputs.branch || github.ref_name }} to ${{ env.HOST }}
              uses: deployphp/action@v1
              with:
                  deployer-version: "7.0.2"
                  private-key: ${{ secrets.PRIVATE_KEY }}
                  dep: deploy --branch=${{ inputs.branch || github.ref_name }} -n ${{ env.HOST }}