name: Install project libs and compile

on:
    workflow_call:
        inputs:
            php:
                required: true
                type: number
            node:
                required: true
                type: number

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ inputs.php }}

            - name: Check Composer lock file is up to date
              run: composer validate --no-check-all

            - name: Install Composer dependencies
              run: composer install --no-progress --prefer-dist --optimize-autoloader

            - name: Installation de NodeJS ${{ inputs.node }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ inputs.node }}

            - name: Installation des dépendances NPM
              run: npm ci

            - name: Lancement des test NPM
              run: npm run test --if-present

            - name: Compilation du front
              run: npm run build --if-present