name: Approve and Merge Dependabot PR

on:
    pull_request:
    pull_request_target:
        branches:
            - main
            - master

permissions:
    pull-requests: write
    issues: write
    repository-projects: write
    contents: write

jobs:
    auto_approve_and_merge:
        uses: agence-adeliom/github-actions/.github/workflows/callable-dependabot-approve-merge.yml@main
