name: Deployer Deploy Only

on:
    push:
        branches:
            - main
            - develop

permissions:
    pull-requests: write
    issues: write
    repository-projects: write
    contents: write

concurrency: deployer_deploy

jobs:
    deploy:
        uses: agence-adeliom/github-actions/.github/workflows/callable-deployer-deploy-only.yml@main
