name: Dependabot WordPress Update

on:
    pull_request:
    pull_request_target:
        branches:
            - main
            - master
    push:
        branches:
            - main
            - master

jobs:
    build:
        uses: agence-adeliom/github-actions/.github/workflows/callable-lumberjack-install.yml@main
        with:
            theme: "adeliom"
            php: "8.1"
            node: "18"
        secrets:
            GRAVITYFORMS_KEY: ${{ secrets.GRAVITYFORMS_KEY }}
            ACF_PRO_KEY: ${{ secrets.ACF_PRO_KEY }}

    wordpress-plugins-update:
        needs: [build]
        uses: agence-adeliom/github-actions/.github/workflows/callable-lumberjack-dependabot-update.yml@main
        with:
            php: "8.1"
            node: "18"
        secrets:
            GRAVITYFORMS_KEY: ${{ secrets.GRAVITYFORMS_KEY }}
            ACF_PRO_KEY: ${{ secrets.ACF_PRO_KEY }}
            NEW_RELIC_API_KEY: ${{ secrets.NEWRELIC_API_KEY }}
