name: Dependabot Symfony Update

on:
    pull_request:
    pull_request_target:
        branches:
            - main
            - master
    push:
        branches:
            - main
            - master

jobs:
    build:
        uses: agence-adeliom/github-actions/.github/workflows/callable-symfony-install.yml@main
        with:
            php: "8.1"
            node: "18"

    symfony-plugins-update:
        needs: [build]
        uses: agence-adeliom/github-actions/.github/workflows/callable-symfony-dependabot-update.yml@main
        with:
            php: "8.1"
            node: "18"
        secrets:
            NEW_RELIC_API_KEY: ${{ secrets.NEWRELIC_API_KEY }}
