name: Deployer Symfony

on:
    push:
        branches:
            - main
            - develop

jobs:
    deploy:
        uses: agence-adeliom/github-actions/.github/workflows/callable-symfony-deployer.yml@main
        with:
            php: "8.1"
            node: "16"
            branch: ${{ github.ref_name }}
        secrets:
            PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
            DEPLOYER_INVENTORY: ${{ secrets.DEPLOYER_INVENTORY }}