name: Dependabot Symfony Update

on:
    pull_request:
    pull_request_target:
        branches:
            - main
            - master
    push:
        branches:
            - main
            - master

env:
    PHP_VERSION: "8.1"
    NODE_VERSION: "18"

jobs:
    build:
        uses: agence-adeliom/github-actions/.github/workflows/callable-install-symfony.yml@main
        with:
            php: ${{ env.PHP_VERSION }}
            node: ${{ env.NODE_VERSION }}

    symfony-plugins-update:
        needs: [build]
        uses: agence-adeliom/github-actions/.github/workflows/callable-symfony-dependabot-update.yml@main
        with:
            php: ${{ env.PHP_VERSION }}
            node: ${{ env.NODE_VERSION }}
        secrets:
            NEW_RELIC_API_KEY: ${{ secrets.NEWRELIC_API_KEY }}